apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web-service
    app: portfolio-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: web-pod
    app: portfolio-app
